### ISSUE TITLE
CMake Error: 

### ISSUE THREAD

**Issue by zjb1001** [cozis/microtcp#3]
Error: The source directory "/home/pg/GitPlayground/microtcp/3p/libtuntap" does not appear to contain CMakeLists.txt.

it related with the Makefile Line71

cmake .. -G $(CMAKE_GENERATOR) -DBUILD_TESTING=OFF -DCMAKE_C_COMPILER=$(CC) -DCMAKE_CXX_COMPILER=$(CXX) -DCMAKE_BUILD_TYPE=Debug && \

Could you share the cmakelists.txt to your repo?

**Comment by cozis** [comment]
Hei! It appears your message wasn't formatted correctly and can't quite decipher it. I'm guessing you were trying to paste the snippet of the makefile.

Looks like something's wrong in the 3p/libtuntap. Did you clone using the `--recursive` flag? If you're not sure, try cloning it again

**Comment by zjb1001** [comment]
Great, you are right. I lost --recursive flag and try it again.  It works well.

By the way, It is better to "mkdir obj out" at the begging of makefile and remove them in “Clean”;

During my practice, I add then manually, Until  I try "make clean" again, find both "obj" and "out" had been created.
